pipeline {
    agent {
    node {
        label 'slave1'
    }
 
}

    stages {
      stage('clean up') {
            steps {
                echo 'Hello build dir'
                deleteDir()
            }
        }
    }
}
